title: Japan Forever
email: japan@prevole.ch
description: Un travail de diplôme pas comme les autres
baseurl: ""
url: "https://japan.prevole.ch"
#twitter_username: jekyllrb
#github_username:  jekyll

theme: minima

excerpt_separator: <!--more-->

gems:
  - jemoji

plugins:
  - jekyll-feed
  - jemoji

exclude:
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
